env:
  es6: true
  node: true
plugins:
  - functional
overrides:
  - env:
      jest: true
    files:
      - __mocks__/**/*.js
      - src/**/*.spec.js
      - test/**/*.js
    rules:
      'max-lines': 0
      'max-lines-per-function': off
parserOptions:
  ecmaVersion: 10
  project: tsconfig.json
  sourceType: module
extends:
  - 'eslint:recommended'
  - 'airbnb-base'
